### ISSUE TITLE
Typing and erasing some text does not update the rendered view

### ISSUE THREAD

**Issue by gchudnov** [TailorDev/monod#125] opened 2016-04-21 05:52 UTC
1. Open https://monod.lelab.tailordev.fr
2. Type some text
3. Erase it

There should be some leftover characters on the rendered view.
Chrome 50,
Firefox 47.0a2 (2016-04-19)

**Comment by jmaupetit** [comment] 2016-04-21 22:47
As for #127 I think it's a Preview component update issue, but i cannot reproduce it.

**Comment by willdurand** [comment] 2016-04-22 10:09
I can reproduce this bug too.. I

**Comment by willdurand** [comment] 2016-04-22 13:21
Found the root cause. Should be fixed now.

**Closed** 2016-04-22 13:21 UTC
Labels: bug

**Comment by gchudnov** [comment] 2016-04-22 18:53
Thank you!

**Comment by willdurand** [comment] 2016-04-22 19:05
Thank you for reporting the issue!
